### ISSUE TITLE
'plugin:react/jsx-runtime' 플러그인을 사용합니다.

### ISSUE THREAD

**Issue by polysiya** [titicacadev/eslint-config-triple#174]
### AS-IS: Rule of Standard

`'react/react-in-jsx-scope': 'error'`

### TO-BE

React 17을 사용하는 곳이 많아졌으므로 [eslint-plugin-react#configuration](https://github.com/yannickcr/eslint-plugin-react#configuration) 가이드에 따라 `'plugin:react/jsx-runtime'` 플러그인을 사용하면 좋겠습니다.

---

> 댓글로 이모지 또는 새로운 의견을 남겨주세요~  
> ex) - :three: : 나는 요래조래

- :one: : 기존안 유지
- :two: : 제안대로 수정

**Comment by zprime0920** [comment]
팀원이 많아져서 그냥 @titicacadev/frontend 태그하기로 했습니당

**Comment by zprime0920** [comment]
저는 2️⃣

**Comment by kooinsung** [comment]
저도 2️⃣

**Comment by inbeom** [comment]
:two: 좋아용

**Comment by torres-triple** [comment]
2️⃣

**Comment by pgs787** [comment]
2️⃣번 입니다!! 🙇

**Comment by zhsks528** [comment]
저도 2️⃣  👍
