### ISSUE TITLE
babel을 통과하지 않는 js 파일을 린트할 때 바벨을 요구하는 문제

### ISSUE THREAD

**Issue by zprime0920** [titicacadev/eslint-config-triple#175]
## 문제점

babel을 사용하지 않는 프로젝트에서 `.eslintrc.js`, `next.config.js` 같은 설정 js 파일이나 스크립트용 js 파일을 린트할 때 babel 설정을 찾을 수 없다는 오류가 발생합니다.

babel을 사용하는 프로젝트는 바벨 설정이 있기 때문에 기본 js 파일을 린트할 때 오류가 없습니다.

## 해결책

`@babel/parser`를 기본 파서에서 제거하고,
`create-config`에서 `babel.config.js` 파일이 존재할 때만 `@babel/eslint-parser`를 설정하도록 하면 어떨까요?

cc. @polysiya

**Comment by polysiya** [comment]
괜찮은 방법인 것 같습니다 👍
