### ISSUE TITLE
[Rule] 블록의 curly 룰을 모든 경우에 적용하는 것으로 바꾸는 것은 어떨까요?

### ISSUE THREAD

**Issue by guswl98** [titicacadev/eslint-config-triple#192]
@titicacadev/frontend

### AS-IS: Rule of Standard

[블록](https://github.com/titicacadev/eslint-config-triple/blob/main/STYLE_GUIDE.md#%EB%B8%94%EB%A1%9D)의 `curly` 룰에 관한 것입니다.
`eslint-config-standard` 에서 `curly` rule을 아래와 같이 적용하고 있습니다. 
```
"curly": ["error", "multi-line"]
```
따라서 구문이 한 줄인 경우에는 룰에 위배되지 않는 것으로 판단합니다. 한 줄인 경우에는 룰을 통과하고 여러 줄인 경우에는 lint error를 발생시키는 상황은 일관성이 없다고 생각합니다. 

### TO-BE

룰을 아래와 같이 바꾸어 모든 경우에 `curly`를 적용시키는 것은 어떨까요?
```
"curly": ["error"]
```

---

> 댓글로 이모지 또는 새로운 의견을 남겨주세요~  
> ex) - :three: : 나는 요래조래

- :one: : 기존안 유지
- :two: : 제안대로 수정

**Comment by zprime0920** [comment]
#42 #46 에서 논의하고 반영했던 내용인데 혹시 지금 오류가 안 나나요?
[코딩 가이드에도 모든 블록에 중괄호를 사용하도록 이야기하고 있으니](https://github.com/titicacadev/eslint-config-triple/blob/main/STYLE_GUIDE.md#%EB%B8%94%EB%A1%9D) 만약 린트 오류가 나지 않는다면 버그로 보고 수정해야겠어요.

**Comment by guswl98** [comment]
문제가 났던 게 이 이유 때문이 아니었네요! 닫도록 하겠습니다 🙂
