### ISSUE TITLE
린터 자체와 플러그인을 peer 의존성으로 바꾸는 건 어떨까요?

### ISSUE THREAD

**Issue by zprime0920** [titicacadev/eslint-config-triple#199]
[ESLint 문서](https://eslint.org/docs/latest/developer-guide/shareable-configs#publishing-a-shareable-config)에 따르면 `eslint`와 plugin을 `peerDependencies`로 설치하라고 이야기합니다.

`dependencies`로 의존성을 설치하면 의존성을 직접 설치할 필요가 없기 때문에 편리하지만, 버전을 사용자가 컨트롤 할 수 없는 문제가 있습니다. #189 이슈도 비슷한 문제로 추정됩니다.

create-triple-app에서는 sharable config로 `eslint-config-react-app`을 관리하고 있고, 플러그인과 eslint 설치는 `react-scripts`에서 담당하고 있습니다. standard에서도 `eslint-config-starndard`를 관리하고 있고 실제 의존성 설치는 `standard` 패키지에서 담당합니다. 우리도 이러한 패턴을 따라가면 어떨까요?

`eslint-config-react-app` (플러그인은 실수로 디펜던시가 된 것 같습니다. 이에 관련한 이슈가 생성되어있는 상태입니다. https://github.com/facebook/create-react-app/issues/11828)

https://github.com/facebook/create-react-app/blob/cee26589ff919e946030a5651a93ccba78a93293/packages/eslint-config-react-app/package.json#L19-L21

`react-scripts`

https://github.com/facebook/create-react-app/blob/cee26589ff919e946030a5651a93ccba78a93293/packages/react-scripts/package.json#L46

`eslint-config-standard`

https://github.com/standard/eslint-config-standard/blob/bcd019906cd379be04ef8e6347e108bad4fc448d/package.json#L51-L56

`standard`

https://github.com/standard/standard/blob/3bfa8525387d8b549f57cb1e3607d8c5c6f2817d/package.json#L17-L24

**Comment by zprime0920** [comment]
그런데 플러그인에서 sharable config을 제공하고, 그걸 우리가 확장하고 있는 형태라서 양쪽 모두로 해석될 수 있다는 점이 조금 애매하네요.

**Comment by inbeom** [comment]
cra에서 설치가 제대로 안 되는 것도, 저런 Usage 때문인 것이려나요 🤔 가이드대로 가는 게 좋을거같긴 한데, Major정도는 픽스해야 하겠지요?

**Comment by zprime0920** [comment]
> cra에서 설치가 제대로 안 되는 것도, 저런 Usage 때문인 것이려나요 🤔 가이드대로 가는 게 좋을거같긴 한데, Major정도는 픽스해야 하겠지요?

넵 cra의 react-scripts랑 의존하는 패키지의 버전이 다른 패키지들이 `node_modules/eslint-config-triple/node_modules`에 설치되면서 의존성을 찾지 못하는 문제였던 거 같아요. #198 으로 픽스했을 땐 정상 작동하는 걸 확인했습니다..!
